### ISSUE TITLE
Cannot install stern

### ISSUE THREAD

**Issue by dhoeric** [wercker/stern#8] opened 2016-11-04 02:52 UTC
Maybe a silly question, I am a novice on golang and I try to install stern on my own machine (with `go get -u github.com/wercker/stern`)

```
package k8s.io/client-go/1.4/kubernetes: cannot find package "k8s.io/client-go/1.4/kubernetes" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/k8s.io/client-go/1.4/kubernetes (from $GOROOT)
	/Users/eric/go/src/k8s.io/client-go/1.4/kubernetes (from $GOPATH)
package k8s.io/client-go/1.4/tools/clientcmd: cannot find package "k8s.io/client-go/1.4/tools/clientcmd" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/k8s.io/client-go/1.4/tools/clientcmd (from $GOROOT)
	/Users/eric/go/src/k8s.io/client-go/1.4/tools/clientcmd (from $GOPATH)
package k8s.io/client-go/1.4/kubernetes/typed/core/v1: cannot find package "k8s.io/client-go/1.4/kubernetes/typed/core/v1" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/k8s.io/client-go/1.4/kubernetes/typed/core/v1 (from $GOROOT)
	/Users/eric/go/src/k8s.io/client-go/1.4/kubernetes/typed/core/v1 (from $GOPATH)
package k8s.io/client-go/1.4/pkg/api: cannot find package "k8s.io/client-go/1.4/pkg/api" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/k8s.io/client-go/1.4/pkg/api (from $GOROOT)
	/Users/eric/go/src/k8s.io/client-go/1.4/pkg/api (from $GOPATH)
package k8s.io/client-go/1.4/pkg/api/v1: cannot find package "k8s.io/client-go/1.4/pkg/api/v1" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/k8s.io/client-go/1.4/pkg/api/v1 (from $GOROOT)
	/Users/eric/go/src/k8s.io/client-go/1.4/pkg/api/v1 (from $GOPATH)
package k8s.io/client-go/1.4/pkg/watch: cannot find package "k8s.io/client-go/1.4/pkg/watch" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/k8s.io/client-go/1.4/pkg/watch (from $GOROOT)
	/Users/eric/go/src/k8s.io/client-go/1.4/pkg/watch (from $GOPATH)
package k8s.io/client-go/1.4/rest: cannot find package "k8s.io/client-go/1.4/rest" in any of:
	/usr/local/Cellar/go/1.7.3/libexec/src/k8s.io/client-go/1.4/rest (from $GOROOT)
	/Users/eric/go/src/k8s.io/client-go/1.4/rest (from $GOPATH)
```

Is there any package management tool do I need to install as well?

**Comment by chrishiestand** [comment] 2016-11-04 21:24
duplicate of https://github.com/wercker/stern/issues/6

**Comment by akupila** [comment] 2016-11-08 15:16
Closing as duplicate of #6. Not at all a silly question, sorry for the confusion (see https://github.com/wercker/stern/issues/6#issuecomment-259163640)

**Closed by akupila** 2016-11-08 15:16 UTC
